// ContentsViewerMsgs.h
#ifndef _CONTENTSVIEWERMSGS_H_
#define _CONTENTSVIEWERMSGS_H_

#define INFO 	0
#define WARN	1
#define ERR 	2

typedef enum _stIndexType
{
	NormIndexTyp = 0,
	HeadIndexTyp,
	SpecificIndexTyp
} stIndexType_t;

#define SCRIPTMSG  						(WM_USER + 1000)

#define	CVM_LOGA						(SCRIPTMSG + 1000)
#define	CVM_LOGW						(SCRIPTMSG + 1001)
#define	CVM_SAVE_DOCUMENT				(SCRIPTMSG + 1002)
#define	CVM_RENAME_DOCUMENT				(SCRIPTMSG + 1003)
#define	CVM_OPEN_DOCUMENT				(SCRIPTMSG + 1004)
#define	CVM_FETCH_DOCUMENT				(SCRIPTMSG + 1005)
#define	CVM_UPDATE_DOCUMENT				(SCRIPTMSG + 1006)
#define	CVM_FETCH_SELECTION				(SCRIPTMSG + 1007)
#define	CVM_UPDATE_SELECTION			(SCRIPTMSG + 1008)

#define CVM_UPDATE_CONTENTSVIEW			(SCRIPTMSG + 2001)

#define CVM_EXPORT_CONTENTS				(SCRIPTMSG + 2101)
#define CVM_IMPORT_CONTENTS             (SCRIPTMSG + 2102)

#define	CVM_GET_DOCUMENT				(SCRIPTMSG + 3001)
#define	CVM_SET_DOCUMENT				(SCRIPTMSG + 3002)

#define	CVM_PARSE						(SCRIPTMSG + 3100)

#define	CVM_DEFAULT_REPLACE				(SCRIPTMSG + 3200)
#define	CVM_REPLACE_ALL					(SCRIPTMSG + 3201)
#define	CVM_REPLACE_INBODY				(SCRIPTMSG + 3202)
#define	CVM_REPLACE_INCONTENTS			(SCRIPTMSG + 3203)

#define	CVM_UPDATE_CONTENTS				(SCRIPTMSG + 3300)
#define CVM_NUMBER_CONTENTS				(SCRIPTMSG + 3301)
#define CVM_ALIGN_CONTENTSNUMBER       	(SCRIPTMSG + 3302)
#define CVM_TRIM_CONTENTS               (SCRIPTMSG + 3303)
#define CVM_SORT_CONTENTS               (SCRIPTMSG + 3304)
#define CVM_DEL_DUPLICATECONTENTS 		(SCRIPTMSG + 3305)
#define CVM_MARK_EMPTYCONTENTS    		(SCRIPTMSG + 3306)

#define CVM_BIG5_GBK 					(SCRIPTMSG + 3401)

#define CVM_MERGE_PARAGRAPHS			(SCRIPTMSG + 3501)
#define CVM_ALIGN_PARAGRAPHS            (SCRIPTMSG + 3502)


#endif //_CONTENTSVIEWERMSGS_H_