//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_ABOUTDLG					40000
#define IDC_LINK						(IDD_ABOUTDLG+1000)

#define IDD_CVDLG 						50000

#define IDC_TOOLBAR						(IDD_CVDLG+1000)

#define IDB_TOOLBAR						(IDC_TOOLBAR+100)


#define IDB_PREVPOS						(IDC_TOOLBAR+200)
#define IDB_NEXTPOS						(IDC_TOOLBAR+300)

#define IDB_SCRIPT_MENU					(IDC_TOOLBAR+400)
#define IDM_SCRIPT						(IDB_SCRIPT_MENU+10)
#define IDM_SCRIPT_FIRST				(IDM_SCRIPT+1)
#define IDM_SCRIPT_LAST					(IDB_PYSCRIPT_MENU-1)

#define IDB_PYSCRIPT_MENU				(IDC_TOOLBAR+500)
#define IDM_PYSCRIPT					(IDB_PYSCRIPT_MENU+10)
#define IDM_PYSCRIPT_FIRST				(IDM_PYSCRIPT+1)
#define IDM_PYSCRIPT_LAST				(IDB_VIEWLIST-1)

#define IDB_VIEWLIST					(IDC_TOOLBAR+600)
#define IDB_VIEWTREE					(IDC_TOOLBAR+700)
#define IDB_PARSE						(IDC_TOOLBAR+800)

#define IDB_EXTRA_MENU					(IDC_TOOLBAR+900)

#define IDM_EXTRA						(IDB_EXTRA_MENU+10)	

#define IDM_HEAD_INDEX_CONTENTS			(IDB_EXTRA_MENU+20)
#define IDM_EXPORT_CONTENTS				(IDB_EXTRA_MENU+30)
#define IDM_IMPORT_CONTENTS				(IDB_EXTRA_MENU+40)

#define IDM_STANDARDIZE_CONTENSTS		(IDB_EXTRA_MENU+50)
#define IDM_SC_INTO_NUMBER				(IDM_STANDARDIZE_CONTENSTS+1)
#define IDM_SC_ALIGN_NUMBER         	(IDM_STANDARDIZE_CONTENSTS+2)
#define IDM_SC_TRIM_CONTENTS        	(IDM_STANDARDIZE_CONTENSTS+3)
#define IDM_SC_SORT_CONTENTS			(IDM_STANDARDIZE_CONTENSTS+4)
#define IDM_SC_DEL_DUPLICATECONTENTS	(IDM_STANDARDIZE_CONTENSTS+5)
#define IDM_SC_MARK_EMPTYCONTENTS   	(IDM_STANDARDIZE_CONTENSTS+6)

#define IDM_BIG5_GBK					(IDB_EXTRA_MENU+60)
#define IDM_MERGE_PARAGRAPHS            (IDB_EXTRA_MENU+70)
#define IDM_ALIGN_PARAGRAPHS            (IDB_EXTRA_MENU+80)

#define IDC_LISTVIEW					(IDD_CVDLG+2000)
#define IDM_CONTEXT_CONTENT				(IDC_LISTVIEW+100)
#define IDM_DEL_CONTENTS				(IDM_CONTEXT_CONTENT+10)
#define IDM_CUT_CONTENTS				(IDM_CONTEXT_CONTENT+20)
#define IDM_INSERT_CONTENTS_BEFORE		(IDM_CONTEXT_CONTENT+30)
#define IDM_SELECT_CONTENTS				(IDM_CONTEXT_CONTENT+40)

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
